# Generated by Django 5.2.7 on 2025-11-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='confirmation_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jobs.jobrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
