# Generated by Django 5.2.7 on 2026-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobrequest_completed_at_jobrequest_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='trade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
