# Generated by Django 5.2.7 on 2026-02-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='JobRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_requests/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.jobrequest')),
            ],
        ),
    ]
