# Generated by Django 5.2.7 on 2026-02-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobreview_photo_jobrequestimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenJobCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('confirmation_generated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_confirmation', max_length=25)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='jobs.job')),
                ('tradesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_open_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('job', 'tradesman')},
            },
        ),
    ]
